"""empty message

Revision ID: e4e0a8446f9b
Revises: 
Create Date: 2020-12-03 19:45:47.566299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4e0a8446f9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('activation', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('student')
    op.drop_table('grade')
    op.drop_table('sheet1')
    op.drop_table('app_weather')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_weather',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('city', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('ymd', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('tianqi', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('bWendu', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('yWendu', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('fenli', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('fenxiang', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('yer', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.Column('month', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sheet1',
    sa.Column('学号', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('身份证件号', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('grade',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['grade.id'], name='student_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
